import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { resolve } from 'node:path'
import { spawnSync } from 'node:child_process'

const root = fileURLToPath(new URL('../../../', import.meta.url))
const target = resolve(root, 'apps/web/src/features/gpu/generated')
const check = process.argv.includes('--check')
mkdirSync(target, { recursive: true })
function emit(name, content) {
  const path = resolve(target, name)
  if (check) {
    if (readFileSync(path, 'utf8') !== content)
      throw new Error(`Generated GPU contract drift: ${name}`)
  } else writeFileSync(path, content)
}
const abiNames = [
  'ILendingVaultV2',
  'ICreditFacilityManager',
  'IRepaymentRouter',
  'GpuTestToken',
]
for (const name of abiNames) {
  const result = spawnSync('forge', ['inspect', name, 'abi', '--json'], {
    cwd: root,
    encoding: 'utf8',
    maxBuffer: 8_000_000,
  })
  if (result.status !== 0)
    throw new Error(`forge inspect ${name} failed: ${result.stderr}`)
  emit(
    `${name}.ts`,
    `// Generated by npm run generate:gpu. Do not edit.\nexport const ${name}Abi = ${JSON.stringify(JSON.parse(result.stdout), null, 2)} as const\n`,
  )
}
const python =
  process.env.GPU_TYPES_PYTHON || resolve(root, '.venv-py313/bin/python')
const result = spawnSync(
  python,
  [
    '-c',
    'import json; from hashcredit_api.gpu.app import create_app; print(json.dumps(create_app().openapi()))',
  ],
  { cwd: root, encoding: 'utf8', maxBuffer: 8_000_000 },
)
if (result.status !== 0)
  throw new Error(`OpenAPI export failed: ${result.stderr}`)
const openapi = JSON.parse(result.stdout)
function convert(schema = {}) {
  if (schema.$ref) return schema.$ref.split('/').at(-1)
  if (schema.const !== undefined) return JSON.stringify(schema.const)
  if (schema.enum)
    return schema.enum.map((value) => JSON.stringify(value)).join(' | ')
  if (schema.anyOf || schema.oneOf)
    return (schema.anyOf || schema.oneOf).map(convert).join(' | ')
  if (schema.type === 'array') return `Array<${convert(schema.items)}>`
  if (schema.type === 'object' || schema.properties) {
    if (!schema.properties)
      return `Record<string, ${typeof schema.additionalProperties === 'object' ? convert(schema.additionalProperties) : 'unknown'}>`
    return `{ ${Object.entries(schema.properties)
      .map(
        ([key, value]) =>
          `${JSON.stringify(key)}${schema.required?.includes(key) ? '' : '?'}: ${convert(value)}`,
      )
      .join('; ')} }`
  }
  return (
    {
      string: 'string',
      integer: 'number',
      number: 'number',
      boolean: 'boolean',
      null: 'null',
    }[schema.type] || 'unknown'
  )
}
emit(
  'api.ts',
  '// Generated from GPU OpenAPI by npm run generate:gpu. Do not edit.\n' +
    Object.entries(openapi.components.schemas)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([name, schema]) => `export type ${name} = ${convert(schema)}\n`)
      .join(''),
)
console.log(
  `GPU generation ${check ? 'check' : 'write'} passed: ${abiNames.length} ABIs and ${Object.keys(openapi.components.schemas).length} DTOs`,
)
