"""ProviderAdapter contract, typed I/O, errors, and the LOCAL mock harness (GPU-019)."""

from .base import (
    MOCK_SLUG_PREFIXES,
    ProviderAdapter,
    assert_native_capable,
    assert_production_admissible,
    check_freshness,
    is_mock_slug,
)
from .errors import (
    AuthError,
    ExpiredData,
    MalformedResponse,
    MissingUnit,
    NotNativeCapable,
    NotProductionAdmissible,
    ProviderAdapterError,
    RateLimited,
    UnsupportedChainError,
    UnsupportedOperation,
)
from .mock import MockProviderAdapter
from .types import (
    AccountRef,
    AdapterIdentity,
    AssetListing,
    Capabilities,
    ClaimRequest,
    ClaimResult,
    ControlChangeRequest,
    ControlChangeResult,
    ControlStateObservation,
    Cursor,
    Page,
    RevenueObservation,
    SettlementObservation,
    Support,
    Window,
)

__all__ = [
    "MOCK_SLUG_PREFIXES",
    "AccountRef",
    "AdapterIdentity",
    "AssetListing",
    "AuthError",
    "Capabilities",
    "ClaimRequest",
    "ClaimResult",
    "ControlChangeRequest",
    "ControlChangeResult",
    "ControlStateObservation",
    "Cursor",
    "ExpiredData",
    "MalformedResponse",
    "MissingUnit",
    "MockProviderAdapter",
    "NotNativeCapable",
    "NotProductionAdmissible",
    "Page",
    "ProviderAdapter",
    "ProviderAdapterError",
    "RateLimited",
    "RevenueObservation",
    "SettlementObservation",
    "Support",
    "UnsupportedChainError",
    "UnsupportedOperation",
    "Window",
    "assert_native_capable",
    "assert_production_admissible",
    "check_freshness",
    "is_mock_slug",
]
